# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kameo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kameo

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'Kameo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KameoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
