# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kameo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  pod 'react-native-safari-view', :path => '../node_modules/react-native-safari-view'

end

